# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.network "public_network", ipv6:false
  
  config.vm.box = "oracle64"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  #
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.synced_folder "F:/Instaladores/EVOLUCION", "/vagrant_data"
  
  config.vm.provision :puppet do |puppet|
    puppet.module_path    = "./modules"
    puppet.options = "--verbose --hiera_config /vagrant/hiera.yaml"
    puppet.manifests_path = "./"
    puppet.facter = {
      "is_vagrant" => true,
    }
  end 

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :mysql do |cnf|
    cnf.vm.box      = "oracle64"
    cnf.vm.hostname = "mysql.home"
    # cnf.vm.network :public_network
    # cnf.vm.network :private_network, ip: "10.0.0.100"
    
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbsrvr1"]
    end
  end   

end
